# Generated by Django 5.1.7 on 2025-03-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_admin_rename_countrycodes_countrycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='socre',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
