# Generated by Django 5.1.7 on 2025-03-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_phrase_keyword_socre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='socre',
            new_name='score',
        ),
    ]
